/* eslint-disable */
// This file was autogenerated from DMN file

const {dmnRunService} = require("@adinsure/runtime");
const {ChronoUnit, LocalDate} = require('@js-joda/core');

module.exports = function businessRule(input, options) {
    return dmnRunService.runService(input, service_CoveragesForSelectedSubtypeAndType, options);
};

const service_CoveragesForSelectedSubtypeAndType = {
    "decisions": {
        "CoveragesForSelectedSubtypeAndType": {
            expression(context) { 
                return dmnRunService.applyHitPolicy("COLLECT", "", 
                    [
                        { condition: context["objectType"] == "vehicle" && (context["isMainCoverage"] == null || context["isMainCoverage"] == true), outputs: "mtpl" },
                        { condition: context["objectType"] == "vehicle" && (context["isMainCoverage"] == null || context["isMainCoverage"] == true), outputs: "mtplPlus" },
                        { condition: context["objectType"] == "vehicle" && (context["isMainCoverage"] == null || context["isMainCoverage"] == true), outputs: "casco" },
                        { condition: context["objectType"] == "vehicle" && (context["isMainCoverage"] == null || context["isMainCoverage"] == true), outputs: "accident" },
                    ]
                        .filter(r => r.condition).map(r => r.outputs)
                );
            },
            requiredDecisions: []
        }
    },
    "outputDecisions": ["CoveragesForSelectedSubtypeAndType"],
    "unboxOutput": true
};
