/* eslint-disable */
// This file was autogenerated from DMN file

const {dmnRunService} = require("@adinsure/runtime");
const {ChronoUnit, LocalDate} = require('@js-joda/core');

module.exports = function businessRule(input, options) {
    return dmnRunService.runService(input, service_CheckCoverageCombinations, options);
};

const service_CheckCoverageCombinations = {
    "decisions": {
        "CheckCoverageCombinations": {
            expression(context) { 
                return dmnRunService.evaluateContextExpression(context, (context) => {
                    return(
                        context["Mock"] = (
                            undefined
                        ),
                        (
                            context["Mock"]
                        ))
                });
            },
            requiredDecisions: []
        }
    },
    "outputDecisions": ["CheckCoverageCombinations"],
    "unboxOutput": true
};
