/* eslint-disable */
// This file was autogenerated from DMN file

const {dmnRunService} = require("@adinsure/runtime");
const {ChronoUnit, LocalDate} = require('@js-joda/core');
const {MapCoverageAttributes} = require("@config-triglav-si/motor-insurance-product/lib/MotorQuoteMapCoverageAttributes"); // MotorQuoteMapCoverageAttributes

module.exports = function businessRule(input, options) {
    return dmnRunService.runService(input, service_MapCoverageAttributes, options);
};

const service_MapCoverageAttributes = {
    "decisions": {
        "MapCoverageAttributes": {
            expression(context) { 
                return dmnRunService.evaluateContextExpression(context, (context) => {
                    return(
                        context["mock"] = (
                            undefined
                        ),
                        (
                            MapCoverageAttributes(context["__input__"])
                        ))
                });
            },
            requiredDecisions: []
        }
    },
    "outputDecisions": ["MapCoverageAttributes"],
    "unboxOutput": true
};
