/* eslint-disable */
// This file was autogenerated from DMN file

const {dmnRunService} = require("@adinsure/runtime");
const {ChronoUnit, LocalDate} = require('@js-joda/core');

module.exports = {
    CheckCoverageCombinations: function(input) { return dmnRunService.runService(input, service_CheckCoverageCombinations);}, 
};

const service_CheckCoverageCombinations = {
    "decisions": {
        "CheckCoverageCombinations": {
            expression(context) { 
                return dmnRunService.applyHitPolicy("COLLECT", "", 
                    [
                        { condition: true, outputs: {"tariffCode": "Casco", "coverageAvailability": "optional"} },
                        { condition: true, outputs: {"tariffCode": "CombinationB", "coverageAvailability": "optional"} },
                        { condition: true, outputs: {"tariffCode": "MtplTariff", "coverageAvailability": "optional"} },
                        { condition: true, outputs: {"tariffCode": "MtplPlus", "coverageAvailability": "optional"} },
                    ]
                        .filter(r => r.condition).map(r => r.outputs)
                );
            },
            requiredDecisions: []
        }
    },
    "outputDecisions": ["CheckCoverageCombinations"],
    "unboxOutput": true
};
