/* eslint-disable */
// This file was autogenerated from DMN file

const {dmnRunService} = require("@adinsure/runtime");
const {ChronoUnit, LocalDate} = require('@js-joda/core');

module.exports = {
    MapContractAttributes: function(input) { return dmnRunService.runService(input, service_MapContractAttributes);}, 
};

const service_MapContractAttributes = {
    "decisions": {
        "MapContractAttributes": {
            expression(context) { 
                return dmnRunService.evaluateContextExpression(context, (context) => {
                    return(
                        context["correctionType"] = (
                            context["uwCorrections"] && context["uwCorrections"]["correctionType"]
                        ), 
                        context["manualRiskAdjustment"] = (
                            context["uwCorrections"] && context["uwCorrections"]["manualRiskAdjustment"]
                        ), 
                        context["startDate"] = (
                            context["contractDuration"] && context["contractDuration"]["startDate"]
                        ), 
                        context["dateSynchronization"] = (
                            context["contractDuration"] && context["contractDuration"]["dateSynchronization"]
                        ),
                        undefined)
                });
            },
            requiredDecisions: []
        }
    },
    "outputDecisions": ["MapContractAttributes"],
    "unboxOutput": true
};
