/* eslint-disable */
// This file was autogenerated from DMN file

const {dmnRunService} = require("@adinsure/runtime");
const {ChronoUnit, LocalDate} = require('@js-joda/core');

module.exports = {
    TruckCoveragePackageDefinition: function(input) { return dmnRunService.runService(input, service_TruckCoveragePackageDefinition);}, 
};

const service_TruckCoveragePackageDefinition = {
    "decisions": {
        "TruckCoveragePackageDefinition": {
            expression(context) { 
                return dmnRunService.applyHitPolicy("UNIQUE", "", 
                    [
                        { condition: context["packageName"] == "Small" && context["massAboveLimit"] == true, outputs: {"mtpl": true, "mtplPlus": true, "casco": false, "combinationB": false, "combinationD": false, "combinationE": false, "combinationJ": false, "combinationK": false, "unbreakableInsurance": false, "carAssistance": false, "legalProtection": false, "accidentInsurance": false} },
                        { condition: context["packageName"] == "Small" && context["massAboveLimit"] == false, outputs: {"mtpl": true, "mtplPlus": true, "casco": false, "combinationB": false, "combinationD": false, "combinationE": false, "combinationJ": false, "combinationK": false, "unbreakableInsurance": false, "carAssistance": false, "legalProtection": false, "accidentInsurance": false} },
                        { condition: context["packageName"] == "Large" && context["massAboveLimit"] == true, outputs: {"mtpl": true, "mtplPlus": true, "casco": true, "combinationB": true, "combinationD": false, "combinationE": false, "combinationJ": false, "combinationK": true, "unbreakableInsurance": false, "carAssistance": false, "legalProtection": false, "accidentInsurance": false} },
                        { condition: context["packageName"] == "Large" && context["massAboveLimit"] == false, outputs: {"mtpl": true, "mtplPlus": true, "casco": true, "combinationB": true, "combinationD": false, "combinationE": false, "combinationJ": false, "combinationK": true, "unbreakableInsurance": false, "carAssistance": false, "legalProtection": false, "accidentInsurance": false} },
                        { condition: context["packageName"] == "Comfort" && context["massAboveLimit"] == true, outputs: {"mtpl": false, "mtplPlus": false, "casco": false, "combinationB": false, "combinationD": false, "combinationE": false, "combinationJ": false, "combinationK": false, "unbreakableInsurance": false, "carAssistance": false, "legalProtection": false, "accidentInsurance": false} },
                        { condition: context["packageName"] == "Comfort" && context["massAboveLimit"] == false, outputs: {"mtpl": true, "mtplPlus": true, "casco": true, "combinationB": true, "combinationD": false, "combinationE": false, "combinationJ": false, "combinationK": false, "unbreakableInsurance": false, "carAssistance": true, "legalProtection": false, "accidentInsurance": false} },
                        { condition: true && true, outputs: {"mtpl": false, "mtplPlus": false, "casco": false, "combinationB": false, "combinationD": false, "combinationE": false, "combinationJ": false, "combinationK": false, "unbreakableInsurance": false, "carAssistance": false, "legalProtection": false, "accidentInsurance": false} },
                    ]
                        .filter(r => r.condition).map(r => r.outputs)
                );
            },
            requiredDecisions: []
        }
    },
    "outputDecisions": ["TruckCoveragePackageDefinition"],
    "unboxOutput": true
};
