/* eslint-disable */
// This file was autogenerated from DMN file

const {dmnRunService} = require("@adinsure/runtime");
const {ChronoUnit, LocalDate} = require('@js-joda/core');
const {MapObjectAttributes} = require("@config-triglav-si/motor-insurance-product/lib/MotorQuoteMapObjectAttributes"); // MotorQuoteMapObjectAttributes

module.exports = function businessRule(input, options) {
    return dmnRunService.runService(input, service_MapObjectAttributes, options);
};

const service_MapObjectAttributes = {
    "decisions": {
        "MapObjectAttributes": {
            expression(context) { 
                return dmnRunService.evaluateContextExpression(context, (context) => {
                    return(
                        context["mock"] = (
                            undefined
                        ),
                        (
                            MapObjectAttributes(context["__input__"])
                        ))
                });
            },
            requiredDecisions: []
        }
    },
    "outputDecisions": ["MapObjectAttributes"],
    "unboxOutput": true
};
